theme: jekyll-theme-midnight
encoding: UTF-8

#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: RestStop

# Short bio or description (displayed in the header)
description: It's time to rest!

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars.githubusercontent.com/gazugafan

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: gazugafan/RestStop
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: gazugafan
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: